deploy-conda:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - module load anaconda/3
    - conda build --channel coml --user coml --token $CONDA_TOKEN --skip-existing .
    - conda build purge
