name: zerospeech2020
dependencies:
  - python>=3.6
  - cython
  - h5py
  - joblib
  - numexpr
  - numpy
  - pandas
  - pip
  - pytables
  - pyyaml
  - scipy
  - setuptools
  - pip:
      - git+https://github.com/bootphon/h5features.git@master
      - git+https://github.com/bootphon/ABXpy.git@master
      - git+https://github.com/bootphon/tdev2.git@master
