# Build the zerospeech2020 conda package. Run with "conda build ."

{% set name = 'zerospeech2020' %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

source:
  path: ..

build:
  entry_points:
  {% for entry in data.get('entry_points')['console_scripts'] %}
    - {{ entry }}
  {% endfor %}
  script:
    - python setup.py build
    - python setup.py install

requirements:
    build:
      - python {{ python }}
      - numpy
      - pandas
      - pyyaml
      - joblib
      - psutil
      - abx
      - tde

    run:
      - python {{ python }}
      - numpy
      - pandas
      - pyyaml
      - joblib
      - psutil
      - abx
      - tde

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}
