# Build the zerospeech2020 conda package. Run with "conda build ."

{% set name = 'zerospeech2020' %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

source:
  path: ..

build:
  script:
    - conda install -c coml tde abx=0.4.3 -y
    - python setup.py build
    - python setup.py install

requirements:
    build:
      - python {{ python }}
      - numpy
      - pyyaml
      - joblib
      - psutil

    run:
      - python {{ python }}
      - numpy
      - pyyaml
      - joblib
      - psutil

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}
